/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.ui;

import com.google.inject.Injector;
import fr.inria.diverse.ocllite.ui.internal.OclliteActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OCLliteExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return OclliteActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return OclliteActivator.getInstance().getInjector(OclliteActivator.FR_INRIA_DIVERSE_OCLLITE);
	}
	
}
