/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOCLliteScopeProvider extends DelegatingScopeProvider {
}
