/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.oCLlite;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Else If Then Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.oCLlite.ElseIfThenExp#getCondition <em>Condition</em>}</li>
 *   <li>{@link fr.inria.diverse.oCLlite.ElseIfThenExp#getThen <em>Then</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.oCLlite.OCLlitePackage#getElseIfThenExp()
 * @model
 * @generated
 */
public interface ElseIfThenExp extends OclLExpression
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(OclLExpression)
   * @see fr.inria.diverse.oCLlite.OCLlitePackage#getElseIfThenExp_Condition()
   * @model containment="true"
   * @generated
   */
  OclLExpression getCondition();

  /**
   * Sets the value of the '{@link fr.inria.diverse.oCLlite.ElseIfThenExp#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(OclLExpression value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(OclLExpression)
   * @see fr.inria.diverse.oCLlite.OCLlitePackage#getElseIfThenExp_Then()
   * @model containment="true"
   * @generated
   */
  OclLExpression getThen();

  /**
   * Sets the value of the '{@link fr.inria.diverse.oCLlite.ElseIfThenExp#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(OclLExpression value);

} // ElseIfThenExp
