/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.oCLlite;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.oCLlite.IfExp#getCondition <em>Condition</em>}</li>
 *   <li>{@link fr.inria.diverse.oCLlite.IfExp#getThen <em>Then</em>}</li>
 *   <li>{@link fr.inria.diverse.oCLlite.IfExp#getIfThen <em>If Then</em>}</li>
 *   <li>{@link fr.inria.diverse.oCLlite.IfExp#getElse <em>Else</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.oCLlite.OCLlitePackage#getIfExp()
 * @model
 * @generated
 */
public interface IfExp extends OclLExpression
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(OclLExpression)
   * @see fr.inria.diverse.oCLlite.OCLlitePackage#getIfExp_Condition()
   * @model containment="true"
   * @generated
   */
  OclLExpression getCondition();

  /**
   * Sets the value of the '{@link fr.inria.diverse.oCLlite.IfExp#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(OclLExpression value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(OclLExpression)
   * @see fr.inria.diverse.oCLlite.OCLlitePackage#getIfExp_Then()
   * @model containment="true"
   * @generated
   */
  OclLExpression getThen();

  /**
   * Sets the value of the '{@link fr.inria.diverse.oCLlite.IfExp#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(OclLExpression value);

  /**
   * Returns the value of the '<em><b>If Then</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.oCLlite.OclLExpression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>If Then</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>If Then</em>' containment reference list.
   * @see fr.inria.diverse.oCLlite.OCLlitePackage#getIfExp_IfThen()
   * @model containment="true"
   * @generated
   */
  EList<OclLExpression> getIfThen();

  /**
   * Returns the value of the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' containment reference.
   * @see #setElse(OclLExpression)
   * @see fr.inria.diverse.oCLlite.OCLlitePackage#getIfExp_Else()
   * @model containment="true"
   * @generated
   */
  OclLExpression getElse();

  /**
   * Sets the value of the '{@link fr.inria.diverse.oCLlite.IfExp#getElse <em>Else</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else</em>' containment reference.
   * @see #getElse()
   * @generated
   */
  void setElse(OclLExpression value);

} // IfExp
