/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.oCLlite;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lambda Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.oCLlite.LambdaType#getName <em>Name</em>}</li>
 *   <li>{@link fr.inria.diverse.oCLlite.LambdaType#getArgsTypes <em>Args Types</em>}</li>
 *   <li>{@link fr.inria.diverse.oCLlite.LambdaType#getReturnType <em>Return Type</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.oCLlite.OCLlitePackage#getLambdaType()
 * @model
 * @generated
 */
public interface LambdaType extends OclLType
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.inria.diverse.oCLlite.OCLlitePackage#getLambdaType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.inria.diverse.oCLlite.LambdaType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Args Types</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.oCLlite.OclLType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Args Types</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args Types</em>' containment reference list.
   * @see fr.inria.diverse.oCLlite.OCLlitePackage#getLambdaType_ArgsTypes()
   * @model containment="true"
   * @generated
   */
  EList<OclLType> getArgsTypes();

  /**
   * Returns the value of the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Return Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Type</em>' containment reference.
   * @see #setReturnType(OclLType)
   * @see fr.inria.diverse.oCLlite.OCLlitePackage#getLambdaType_ReturnType()
   * @model containment="true"
   * @generated
   */
  OclLType getReturnType();

  /**
   * Sets the value of the '{@link fr.inria.diverse.oCLlite.LambdaType#getReturnType <em>Return Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Type</em>' containment reference.
   * @see #getReturnType()
   * @generated
   */
  void setReturnType(OclLType value);

} // LambdaType
