/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.oCLlite;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.oCLlite.MapElement#getKey <em>Key</em>}</li>
 *   <li>{@link fr.inria.diverse.oCLlite.MapElement#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.oCLlite.OCLlitePackage#getMapElement()
 * @model
 * @generated
 */
public interface MapElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Key</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' containment reference.
   * @see #setKey(OclLExpression)
   * @see fr.inria.diverse.oCLlite.OCLlitePackage#getMapElement_Key()
   * @model containment="true"
   * @generated
   */
  OclLExpression getKey();

  /**
   * Sets the value of the '{@link fr.inria.diverse.oCLlite.MapElement#getKey <em>Key</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' containment reference.
   * @see #getKey()
   * @generated
   */
  void setKey(OclLExpression value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(OclLExpression)
   * @see fr.inria.diverse.oCLlite.OCLlitePackage#getMapElement_Value()
   * @model containment="true"
   * @generated
   */
  OclLExpression getValue();

  /**
   * Sets the value of the '{@link fr.inria.diverse.oCLlite.MapElement#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(OclLExpression value);

} // MapElement
