/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.oCLlite;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.oCLlite.MapExp#getMapElements <em>Map Elements</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.oCLlite.OCLlitePackage#getMapExp()
 * @model
 * @generated
 */
public interface MapExp extends OclLExpression
{
  /**
   * Returns the value of the '<em><b>Map Elements</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.oCLlite.MapElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Map Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map Elements</em>' containment reference list.
   * @see fr.inria.diverse.oCLlite.OCLlitePackage#getMapExp_MapElements()
   * @model containment="true"
   * @generated
   */
  EList<MapElement> getMapElements();

} // MapExp
