/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.oCLlite;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Null Literal Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.inria.diverse.oCLlite.OCLlitePackage#getNullLiteralExp()
 * @model
 * @generated
 */
public interface NullLiteralExp extends PrimitiveExp
{
} // NullLiteralExp
