/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.oCLlite;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ordered Set Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.inria.diverse.oCLlite.OCLlitePackage#getOrderedSetExp()
 * @model
 * @generated
 */
public interface OrderedSetExp extends CollectionExp
{
} // OrderedSetExp
