/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.ui.tests;

import com.google.inject.Injector;
import fr.inria.diverse.ocllite.ui.internal.OclliteActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class OCLliteUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return OclliteActivator.getInstance().getInjector("fr.inria.diverse.OCLlite");
	}

}
