/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.tests

import com.google.inject.Inject
import fr.inria.diverse.oCLlite.Module
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(OCLliteInjectorProvider)
class OCLliteParsingTest{

	@Inject
	ParseHelper<Module> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
